import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("species map pans on pointer release without rerasterizing during movement", async () => {
  const source = await readFile(new URL("../src/species-map.ts", import.meta.url), "utf8");
  assert.match(source, /centerAfterDrag/);
  assert.match(source, /setPointerCapture/);
  assert.match(source, /pointermove/);
  assert.match(source, /pointerup/);
  assert.match(source, /drag\.moved\|\|Math\.hypot\(finalDx,finalDy\)>7/);
  assert.match(source, /if\(!moved\)/);
  assert.match(source, /c\.center=centerAfterDrag/);
  assert.match(source, /drag to pan/);
  assert.match(source, /regionLabel/);
  assert.match(source, /address\.state\|\|address\.region\|\|address\.province/);
  assert.match(source, /countryCode:String\(address\.country_code/);
  assert.match(source, /image\/webp/);
  assert.match(source, /optimizedImageUrl/);
  assert.match(source, /1280,720/);
  assert.match(source, /loadBoundary/);
  assert.match(source, /polygon_geojson/);
  assert.match(source, /rgba\(0,255,0,0\.33\)/);
  assert.match(source, /stopImmediatePropagation/);
  assert.match(source, /pointerleave/);
  assert.match(source, /event\.deltaY<0/);
  assert.match(source, /loadBoundary\(point\.lat,point\.lon\)/);
  assert.doesNotMatch(source, /if\(isBrazilView\(c\)\)return rasterBrazil/);
  assert.match(source, /KNOWN_VOCAL_RANGES/);
  assert.match(source, /municipalities/);
  assert.match(source, /Faixa empírica/);
  assert.doesNotMatch(source, /BRAZIL_STATE_NAMES|stateAt\(/);
  assert.match(source, /REGION_PAGE_SIZE=300/);
  assert.match(source, /offset<count&&offset<REGION_RECORD_CAP/);
  assert.match(source, /base\.state_province=region\.name/);
  assert.match(source, /base\.country=region\.countryCode/);
  assert.match(source, /mountLeafletSpeciesMap/);
  const leaflet = await readFile(new URL("../src/leaflet-species-map.ts", import.meta.url), "utf8");
  assert.match(leaflet, /tile\.openstreetmap\.org/);
  assert.match(leaflet, /coordinateCache/);
  assert.match(leaflet, /localStorage/);
  assert.match(leaflet, /moveend zoomend resize/);
  assert.match(leaflet, /recordLayer\.clearLayers/);
  assert.match(leaflet, /AdministrativeBoundary/);
});
