type SpectralPoint={timeMs:number;frequencyHz:number;amplitude:number;spectralFlux:number;tonality:number;flatness:number;spectralSpreadHz:number;spectralCrest:number;xyz:[number,number,number]};
type SpectralAnalysis={method?:string;durationMs?:number;points?:SpectralPoint[]};
type TrailPoint={time:number;x:number;y:number;z:number;hue:number;strength:number};

function hsl(h:number,s:number,l:number,a:number){return `hsla(${h},${s}%,${l}%,${a})`;}
function prepare(value:unknown):{points:TrailPoint[];duration:number}{
  const data=value as SpectralAnalysis;
  if(!String(data?.method||"").match(/^(hybrid64-robust-pca3|mfcc40-pca3)/u)||!Array.isArray(data.points))throw new Error("A ponte não retornou uma análise PCA compatível.");
  let smooth=[0,0,0];const points=data.points.slice(0,32768).map((point,index)=>{const xyz=point.xyz||[0,0,0],amp=Math.max(0,Number(point.amplitude)||0)/255,flux=Math.max(0,Number(point.spectralFlux)||0)/255,tonality=Math.max(0,Number(point.tonality)||0)/255,response=.16+flux*.25+(1-tonality)*.12,target=[(Number(xyz[0])||0)/32767,(Number(xyz[1])||0)/32767,(Number(xyz[2])||0)/32767];smooth=index? smooth.map((n,axis)=>n+(target[axis]-n)*response):target;const hz=Math.max(20,Number(point.frequencyHz)||20),ratio=Math.max(0,Math.min(1,Math.log2(hz/20)/Math.log2(18000/20)));return{time:(Number(point.timeMs)||0)/1000,x:smooth[0],y:smooth[1],z:smooth[2],hue:250-ratio*235,strength:.16+tonality*.58+amp*.26};});
  return{points,duration:Math.max((Number(data.durationMs)||0)/1000,points.at(-1)?.time||0)};
}

export function mountDesktopSpectralTrail(audio:HTMLAudioElement,host:HTMLElement,loadAnalysis:()=>Promise<unknown>){
  const shell=host.createDiv({cls:"meta-quest-spectral-desktop"}),toolbar=shell.createDiv({cls:"meta-quest-spectral-toolbar"});toolbar.createSpan({text:"Identidade espectral 3D · PCA híbrida"});
  const rotate=toolbar.createEl("button",{text:"Rotação: desligada"}),reset=toolbar.createEl("button",{text:"Redefinir câmera"}),status=toolbar.createSpan({text:"Analisando áudio…"});
  const canvas=shell.createEl("canvas",{cls:"meta-quest-spectral-canvas",attr:{width:"960",height:"480","aria-label":"Identidade espectral tridimensional híbrida"}}),ctx=canvas.getContext("2d");
  let points:TrailPoint[]=[],duration=0,yaw=-.55,pitch=.28,auto=false,drag:null|{x:number;y:number;yaw:number;pitch:number}=null,frame=0,disposed=false;
  const project=(p:{x:number;y:number;z:number})=>{const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,y=p.y*cp-z*sp,depth=p.y*sp+z*cp+3.2,scale=310/depth;return{x:canvas.width/2+x*scale,y:canvas.height*.55-y*scale,visible:depth>.2};};
  const line=(a:{x:number;y:number;z:number},b:{x:number;y:number;z:number},color="rgba(112,151,190,.2)")=>{if(!ctx)return;const pa=project(a),pb=project(b);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();};
  function label(text:string,p:{x:number;y:number;z:number}){if(!ctx)return;const q=project(p);ctx.fillStyle="rgba(220,237,252,.78)";ctx.font="15px system-ui";ctx.fillText(text,q.x+5,q.y-4);}
  function grid(){for(let i=-5;i<=5;i++){line({x:i/5,y:-1,z:-1},{x:i/5,y:-1,z:1});line({x:-1,y:-1,z:i/5},{x:1,y:-1,z:i/5});line({x:-1,y:i/5,z:-1},{x:1,y:i/5,z:-1});}label("COMPONENTE 1",{x:.55,y:-1,z:1});label("COMPONENTE 2",{x:-1,y:.75,z:-1});label("COMPONENTE 3",{x:1,y:-1,z:.35});}
  function render(){if(disposed||!ctx)return;ctx.fillStyle="#050b13";ctx.fillRect(0,0,canvas.width,canvas.height);grid();if(auto)yaw+=.0025;const identity=audio.ended||(duration>0&&audio.currentTime>=duration-.08&&audio.paused),start=identity?0:Math.max(0,audio.currentTime-3.25),end=identity?duration:audio.currentTime;let previous:ReturnType<typeof project>|null=null;for(const point of points){if(point.time<start||point.time>end){previous=null;continue;}const current=project(point);if(previous&&current.visible){const alpha=identity?Math.max(.18,point.strength*.72):point.strength*Math.max(.12,1-(end-point.time)/3.25);ctx.strokeStyle=hsl(point.hue,88,62,alpha);ctx.lineWidth=identity?1.5:2.2;ctx.beginPath();ctx.moveTo(previous.x,previous.y);ctx.lineTo(current.x,current.y);ctx.stroke();}previous=current;}ctx.fillStyle="rgba(224,238,252,.72)";ctx.font="20px system-ui";ctx.fillText(identity?"assinatura completa · somente linhas":"janela temporal atual · 3,25 s",22,32);frame=requestAnimationFrame(render);}
  rotate.onclick=()=>{auto=!auto;rotate.setText(`Rotação: ${auto?"ligada":"desligada"}`);};reset.onclick=()=>{yaw=-.55;pitch=.28;};canvas.addEventListener("pointerdown",e=>{drag={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener("pointermove",e=>{if(!drag)return;yaw=drag.yaw+(e.clientX-drag.x)*.008;pitch=Math.max(-1.2,Math.min(1.2,drag.pitch+(e.clientY-drag.y)*.008));});canvas.addEventListener("pointerup",()=>drag=null);canvas.addEventListener("pointercancel",()=>drag=null);
  const restart=()=>{};audio.addEventListener("seeked",restart);audio.addEventListener("play",restart);const observer=new MutationObserver(()=>{if(document.contains(shell))return;disposed=true;cancelAnimationFrame(frame);observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});
  void Promise.resolve().then(loadAnalysis).then(value=>{({points,duration}=prepare(value));status.setText(`${points.length.toLocaleString()} pontos · ${duration.toFixed(1)} s`);}).catch(error=>status.setText(`Análise indisponível: ${error instanceof Error?error.message:String(error)}`));render();return shell;
}
