import { tr } from "./i18n";

type SpectralPoint={timeMs:number;frequencyHz:number;amplitude:number;spectralFlux:number;tonality:number;flatness:number;spectralSpreadHz:number;spectralCrest:number;xyz:[number,number,number]};
type SpectralAnalysis={method?:string;duration?:number;durationMs?:number;points?:SpectralPoint[]};
type TrailPoint={time:number;x:number;y:number;z:number;hue:number;strength:number;frequencyHz:number;amplitude:number};
export type SpectralFrequencyRange={minHz:number;maxHz:number};
type TrailOptions={storageKey?:string;onFrequencyRange?:(range:SpectralFrequencyRange)=>void};
export function spectralFrequencyRange(value:unknown):SpectralFrequencyRange|null{const raw=(value as SpectralAnalysis)?.points;if(!Array.isArray(raw))return null;const usable=raw.map(p=>({hz:Number(p.frequencyHz),weight:Math.max(0,Number(p.amplitude)||0)})).filter(p=>Number.isFinite(p.hz)&&p.hz>=20&&p.weight>=18).sort((a,b)=>a.hz-b.hz);if(!usable.length)return null;const total=usable.reduce((sum,p)=>sum+p.weight,0),percentile=(ratio:number)=>{let sum=0;for(const p of usable){sum+=p.weight;if(sum>=total*ratio)return p.hz;}return usable.at(-1)!.hz;};return{minHz:Math.round(percentile(.03)),maxHz:Math.round(percentile(.97))};}

function hsl(h:number,s:number,l:number,a:number){return `hsla(${h},${s}%,${l}%,${a})`;}
function prepare(value:unknown):{points:TrailPoint[];duration:number}{
  const data=value as SpectralAnalysis;
  if(!String(data?.method||"").match(/^(hybrid64-robust-pca3|mfcc40-pca3)/u)||!Array.isArray(data.points))throw new Error("A ponte não retornou uma análise PCA compatível.");
  let smooth=[0,0,0];const points=data.points.slice(0,32768).map((point,index)=>{const xyz=point.xyz||[0,0,0],amp=Math.max(0,Number(point.amplitude)||0)/255,flux=Math.max(0,Number(point.spectralFlux)||0)/255,tonality=Math.max(0,Number(point.tonality)||0)/255,response=.16+flux*.25+(1-tonality)*.12,target=[(Number(xyz[0])||0)/32767,(Number(xyz[1])||0)/32767,(Number(xyz[2])||0)/32767];smooth=index? smooth.map((n,axis)=>n+(target[axis]-n)*response):target;const hz=Math.max(20,Number(point.frequencyHz)||20),ratio=Math.max(0,Math.min(1,Math.log2(hz/20)/Math.log2(18000/20)));return{time:(Number(point.timeMs)||0)/1000,x:smooth[0],y:smooth[1],z:smooth[2],hue:250-ratio*235,strength:.16+tonality*.58+amp*.26,frequencyHz:hz,amplitude:amp};});
  return{points,duration:Math.max(Number(data.duration)||0,(Number(data.durationMs)||0)/1000,points.at(-1)?.time||0)};
}

export function mountDesktopSpectralTrail(audio:HTMLMediaElement,host:HTMLElement,loadAnalysis:()=>Promise<unknown>,options:TrailOptions={}){
  const shell=host.createDiv({cls:"meta-quest-spectral-desktop"}),toolbar=shell.createDiv({cls:"meta-quest-spectral-toolbar"});toolbar.createSpan({text:tr("Identidade espectral 3D · PCA híbrida","3D spectral identity · hybrid PCA")});
  const rotate=toolbar.createEl("button",{text:tr("Rotação: desligada","Rotation: off")}),shape=toolbar.createEl("button",{text:tr("Forma: linhas","Shape: lines")}),zoomOut=toolbar.createEl("button",{text:"Zoom −",attr:{"aria-label":"Reduzir zoom"}}),zoomIn=toolbar.createEl("button",{text:"Zoom +",attr:{"aria-label":"Aumentar zoom"}}),reset=toolbar.createEl("button",{text:tr("Redefinir câmera","Reset camera")}),status=toolbar.createSpan({text:tr("Analisando áudio…","Analyzing audio…")});
  const savedKey=options.storageKey?`meta-quest-spectral-frequency:${options.storageKey}`:"meta-quest-spectral-frequency:default";let saved:{minHz?:number;maxHz?:number}={};try{saved=JSON.parse(localStorage.getItem(savedKey)||"{}");}catch{}const filters=shell.createDiv({cls:"meta-quest-spectral-filters"});const numeric=(label:string,value:string,min:string,max:string,step:string)=>{const wrap=filters.createEl("label");wrap.createSpan({text:label});return wrap.createEl("input",{type:"number",value,attr:{min,max,step}});};const minHz=numeric(tr("Hz mín.","Min Hz"),String(saved.minHz??0),"0","24000","100"),maxHz=numeric(tr("Hz máx.","Max Hz"),String(saved.maxHz??18000),"100","48000","100"),minIntensity=numeric(tr("Intensidade mín. %","Min intensity %"),"0","0","100","1"),windowSeconds=numeric(tr("Janela (s)","Window (s)"),"3.25","0.25","30","0.25"),labelDensity=numeric(tr("Labels %","Labels %"),"18","1","100","1"),saveHz=filters.createEl("button",{text:tr("Salvar Hz","Save Hz")});saveHz.onclick=()=>{localStorage.setItem(savedKey,JSON.stringify({minHz:Number(minHz.value)||0,maxHz:Number(maxHz.value)||18000}));saveHz.setText(tr("Hz salvos ✓","Hz saved ✓"));window.setTimeout(()=>saveHz.setText(tr("Salvar Hz","Save Hz")),1400);};shell.createDiv({cls:"meta-quest-spectral-explanation",text:"Eixos PCA: combinações dos 40 coeficientes MFCC. Eles descrevem forma, contraste e textura do timbre; não representam uma frequência isolada."});const canvas=shell.createEl("canvas",{cls:"meta-quest-spectral-canvas",attr:{width:"960",height:"480","aria-label":"Identidade espectral tridimensional híbrida; use a roda do mouse para zoom"}}),ctx=canvas.getContext("2d");const dashboard=shell.createDiv({cls:"meta-quest-spectral-dashboard"});const panelTitles=[tr("Descritores Hz","Hz descriptors"),tr("Dinâmica dB","dB dynamics"),tr("Mapa tonal","Tone map"),tr("Janela temporal","Time window"),tr("Projeção cepstral","Cepstral projection"),tr("Perfil cromático derivado","Derived chroma profile")];const panelCanvases=panelTitles.map(title=>{const panel=dashboard.createDiv({cls:"meta-quest-spectral-panel"});panel.createDiv({cls:"meta-quest-spectral-panel-title",text:title});return panel.createEl("canvas",{attr:{width:"420",height:"150"}});});
  let points:TrailPoint[]=[],duration=0,yaw=-.55,pitch=.28,zoom=1,auto=false,rectangles=false,drag:null|{x:number;y:number;yaw:number;pitch:number}=null,frame=0,disposed=false;
  const project=(p:{x:number;y:number;z:number})=>{const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,y=p.y*cp-z*sp,depth=p.y*sp+z*cp+3.2,scale=310*zoom/depth;return{x:canvas.width/2+x*scale,y:canvas.height*.55-y*scale,visible:depth>.2};};
  const line=(a:{x:number;y:number;z:number},b:{x:number;y:number;z:number},color="rgba(112,151,190,.2)")=>{if(!ctx)return;const pa=project(a),pb=project(b);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();};
  function label(text:string,p:{x:number;y:number;z:number}){if(!ctx)return;const q=project(p);ctx.fillStyle="rgba(220,237,252,.78)";ctx.font="15px system-ui";ctx.fillText(text,q.x+5,q.y-4);}
  function grid(){for(let i=-5;i<=5;i++){line({x:i/5,y:-1,z:-1},{x:i/5,y:-1,z:1});line({x:-1,y:-1,z:i/5},{x:1,y:-1,z:i/5});line({x:-1,y:i/5,z:-1},{x:1,y:i/5,z:-1});}label("PC1 · forma do espectro (MFCC)",{x:.34,y:-1,z:1});label("PC2 · contraste tímbrico (MFCC)",{x:-1,y:.72,z:-1});label("PC3 · textura espectral (MFCC)",{x:1,y:-1,z:.16});}
  function renderPanels(selected:TrailPoint[]){panelCanvases.forEach((c,index)=>{const x=c.getContext("2d");if(!x)return;x.fillStyle="#030810";x.fillRect(0,0,c.width,c.height);x.strokeStyle="rgba(110,145,180,.18)";for(let g=1;g<5;g++){x.beginPath();x.moveTo(0,g*c.height/5);x.lineTo(c.width,g*c.height/5);x.stroke();}if(!selected.length)return;for(let i=0;i<selected.length;i++){const p=selected[i],px=i/Math.max(1,selected.length-1)*c.width,fy=1-Math.min(1,p.frequencyHz/18000),ay=1-p.amplitude;x.strokeStyle=hsl(p.hue,88,58,.52);x.fillStyle=hsl(p.hue,88,58,.62);if(index===0||index===3){if(i){const q=selected[i-1];x.beginPath();x.moveTo((i-1)/Math.max(1,selected.length-1)*c.width,(1-Math.min(1,q.frequencyHz/18000))*c.height);x.lineTo(px,fy*c.height);x.stroke();}if(index===3){const newest=i===selected.length-1,size=3+p.amplitude*7;x.save();x.strokeStyle=newest?"rgba(255,255,255,.94)":hsl(p.hue,90,64,.78);x.shadowColor=newest?"rgba(255,255,255,.28)":hsl(p.hue,90,60,.3);x.shadowBlur=3;x.strokeRect(px-size/2,fy*c.height-size/2,size,size);x.restore();}}else if(index===1){x.fillRect(px,ay*c.height,2,c.height-ay*c.height);}else if(index===2){x.fillRect(Math.min(1,p.frequencyHz/18000)*c.width,ay*c.height,2,2);}else if(index===4){x.fillRect((p.x+1)*.5*c.width,(1-(p.y+1)*.5)*c.height,2.5,2.5);}else{x.fillRect(((Math.round(12*Math.log2(Math.max(20,p.frequencyHz)/440))+69)%12+12)%12/12*c.width,ay*c.height,3,c.height-ay*c.height);}}});}
  function render(){if(disposed||!ctx)return;ctx.fillStyle="#050b13";ctx.fillRect(0,0,canvas.width,canvas.height);grid();if(auto)yaw+=.0025;const identity=audio.ended||(duration>0&&audio.currentTime>=duration-.08&&audio.paused),windowSize=Math.max(.25,Number(windowSeconds.value)||3.25),low=Math.max(0,Number(minHz.value)||0),high=Math.max(low,Number(maxHz.value)||18000),threshold=Math.max(0,Number(minIntensity.value)||0)/100,labelEvery=Math.max(1,Math.round(100/Math.max(1,Number(labelDensity.value)||18))),start=identity?0:Math.max(0,audio.currentTime-windowSize),end=identity?duration:audio.currentTime;let previous:ReturnType<typeof project>|null=null;const selected=points.filter(point=>point.time>=start&&point.time<=end&&point.frequencyHz>=low&&point.frequencyHz<=high&&point.amplitude>=threshold);let visibleIndex=0;for(const point of selected){visibleIndex++;const current=project(point);if(previous&&current.visible){const alpha=identity?Math.max(.18,point.strength*.72):point.strength*Math.max(.12,1-(end-point.time)/3.25);ctx.strokeStyle=hsl(point.hue,88,62,alpha);ctx.lineWidth=identity?1.5:2.2;ctx.beginPath();ctx.moveTo(previous.x,previous.y);ctx.lineTo(current.x,current.y);ctx.stroke();if(rectangles){const size=4+point.strength*7;ctx.fillStyle=hsl(point.hue,82,58,Math.max(.22,alpha*.72));ctx.fillRect(current.x-size/2,current.y-size/2,size,size);if(visibleIndex%labelEvery===0){ctx.fillStyle="rgba(244,247,255,.9)";ctx.font="9px system-ui";const hz=point.frequencyHz>=1000?`${(point.frequencyHz/1000).toFixed(2)}kHz`:`${Math.round(point.frequencyHz)}Hz`;ctx.fillText(`${point.time.toFixed(2)}s`,current.x+8,current.y-7);ctx.fillText(`${hz} · ${point.amplitude.toFixed(3)}`,current.x+8,current.y+5);const age=Math.max(0,end-point.time),birth=Math.max(0,Math.min(1,1-age/.22));ctx.save();ctx.strokeStyle=birth>0?`rgba(255,255,255,${(.72+birth*.25).toFixed(3)})`:hsl(point.hue,90,64,.86);ctx.shadowColor=birth>0?"rgba(255,255,255,.3)":hsl(point.hue,90,60,.28);ctx.shadowBlur=3;ctx.strokeRect(current.x-size/2-2,current.y-size/2-2,size+4,size+4);ctx.restore();}}}previous=current;}renderPanels(selected);if(identity){const gradient=ctx.createLinearGradient(24,0,canvas.width-24,0);for(let i=0;i<=12;i++)gradient.addColorStop(i/12,hsl(250-i/12*235,90,56,1));ctx.fillStyle=gradient;ctx.fillRect(24,canvas.height-22,canvas.width-48,8);ctx.fillStyle="rgba(225,239,255,.78)";ctx.font="11px system-ui";ctx.fillText(tr("ESPECTRO 20 Hz → 18 kHz","SPECTRUM 20 Hz → 18 kHz"),24,canvas.height-28);}ctx.fillStyle="rgba(224,238,252,.72)";ctx.font="20px system-ui";ctx.fillText(identity?"assinatura completa · somente linhas":`janela temporal atual · ${windowSize.toFixed(2)} s`,22,32);frame=requestAnimationFrame(render);}
  const setZoom=(value:number)=>{zoom=Math.max(.45,Math.min(3.5,value));};rotate.onclick=()=>{auto=!auto;rotate.setText(auto?tr("Rotação: ligada","Rotation: on"):tr("Rotação: desligada","Rotation: off"));};shape.onclick=()=>{rectangles=!rectangles;shape.setText(rectangles?tr("Forma: retângulos + labels","Shape: rectangles + labels"):tr("Forma: linhas","Shape: lines"));};zoomOut.onclick=()=>setZoom(zoom/1.2);zoomIn.onclick=()=>setZoom(zoom*1.2);reset.onclick=()=>{yaw=-.55;pitch=.28;zoom=1;};canvas.addEventListener("wheel",e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.0012));},{passive:false});canvas.addEventListener("pointerdown",e=>{drag={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener("pointermove",e=>{if(!drag)return;yaw=drag.yaw+(e.clientX-drag.x)*.008;pitch=Math.max(-1.2,Math.min(1.2,drag.pitch+(e.clientY-drag.y)*.008));});canvas.addEventListener("pointerup",()=>drag=null);canvas.addEventListener("pointercancel",()=>drag=null);
  const restart=()=>{};audio.addEventListener("seeked",restart);audio.addEventListener("play",restart);const observer=new MutationObserver(()=>{if(document.contains(shell))return;disposed=true;cancelAnimationFrame(frame);observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});
  void Promise.resolve().then(loadAnalysis).then(value=>{({points,duration}=prepare(value));const range=spectralFrequencyRange(value);if(range){options.onFrequencyRange?.(range);status.setText(`${points.length.toLocaleString()} pontos · ${duration.toFixed(1)} s · ${range.minHz.toLocaleString()}–${range.maxHz.toLocaleString()} Hz`);}else status.setText(`${points.length.toLocaleString()} pontos · ${duration.toFixed(1)} s`);}).catch(error=>status.setText(`Análise indisponível: ${error instanceof Error?error.message:String(error)}`));render();return shell;
}
