type Sequence={id:string;sequence:string};
type TreeNode={name?:string;left?:TreeNode;right?:TreeNode;height:number;size:number};

const COLORS={hydrophobic:"#63e6be",polar:"#74c0fc",acidic:"#ff8787",basic:"#b197fc",special:"#ffd166",gap:"#36445a",unknown:"#74839a"};
function residueColor(value:string):string{if("AVILMFWY".includes(value))return COLORS.hydrophobic;if("STNQ".includes(value))return COLORS.polar;if("DE".includes(value))return COLORS.acidic;if("KRH".includes(value))return COLORS.basic;if("CGP".includes(value))return COLORS.special;return value==="-"||value==="."?COLORS.gap:COLORS.unknown;}

export function parseFasta(source:string):Sequence[]{const sequences:Sequence[]=[];let current:Sequence|null=null;for(const original of source.slice(0,500_000).split(/\r?\n/)){const line=original.trim();if(!line||line.startsWith(";"))continue;if(line.startsWith(">")){if(current?.sequence)sequences.push(current);const parts=line.slice(1).trim().split(/\s+/),inline:string[]=[];while(parts.length>1&&/^[A-Z*.-]{12,}$/i.test(parts.at(-1)||""))inline.unshift(parts.pop()||"");const title=parts.join(" ")||`Sequence ${sequences.length+1}`;current=title?{id:title.split(/\s+/)[0],sequence:inline.join("").toUpperCase()}:null;}else{current??={id:"Sequence_1",sequence:""};current.sequence+=(line.toUpperCase().match(/[A-Z*.-]/g)||[]).join("");}if(sequences.length>=127)break;}if(current?.sequence&&sequences.length<128)sequences.push(current);return sequences.filter(item=>item.sequence.length>0);}

export function pDistance(a:string,b:string,maxSites=5000):number{let compared=0,different=0;const length=Math.min(a.length,b.length),step=Math.max(1,Math.ceil(length/maxSites));for(let i=0;i<length;i+=step){const x=a[i],y=b[i];if(!x||!y||x==="-"||y==="-"||x==="."||y==="."||x==="N"||y==="N"||x==="X"||y==="X")continue;compared++;if(x!==y)different++;}return compared?different/compared:1;}

export function buildUpgma(sequences:Sequence[]):TreeNode|null{const selected=sequences.slice(0,64),clusters=selected.map((item,index)=>({node:{name:item.id,height:0,size:1} as TreeNode,members:[index]})),base=selected.map((a,i)=>selected.map((b,j)=>i===j?0:pDistance(a.sequence,b.sequence)));while(clusters.length>1){let ai=0,bi=1,best=Infinity;for(let i=0;i<clusters.length;i++)for(let j=i+1;j<clusters.length;j++){let total=0,count=0;for(const a of clusters[i].members)for(const b of clusters[j].members){total+=base[a][b];count++;}const distance=count?total/count:1;if(distance<best){best=distance;ai=i;bi=j;}}const right=clusters.splice(bi,1)[0],left=clusters.splice(ai,1)[0];clusters.push({node:{left:left.node,right:right.node,height:best/2,size:left.node.size+right.node.size},members:[...left.members,...right.members]});}return clusters[0]?.node??null;}

function drawTree(root:TreeNode,sequences:Sequence[]):HTMLCanvasElement{const leaves:TreeNode[]=[];const collect=(node:TreeNode)=>{if(node.name)leaves.push(node);else{if(node.left)collect(node.left);if(node.right)collect(node.right);}};collect(root);const canvas=document.createElement("canvas"),row=26,margin=24,labelWidth=220;canvas.width=1100;canvas.height=Math.max(180,margin*2+leaves.length*row);const ctx=canvas.getContext("2d")!;ctx.fillStyle="#07111d";ctx.fillRect(0,0,canvas.width,canvas.height);const maxHeight=Math.max(root.height,.0001),xFor=(height:number)=>margin+(maxHeight-height)/maxHeight*(canvas.width-labelWidth-margin*2),positions=new Map<TreeNode,{x:number;y:number}>();leaves.forEach((leaf,index)=>positions.set(leaf,{x:xFor(0),y:margin+index*row+row/2}));const layout=(node:TreeNode):{x:number;y:number}=>{const known=positions.get(node);if(known)return known;const left=layout(node.left!),right=layout(node.right!),point={x:xFor(node.height),y:(left.y+right.y)/2};positions.set(node,point);return point;};layout(root);const paint=(node:TreeNode)=>{if(node.name)return;const point=positions.get(node)!,left=positions.get(node.left!)!,right=positions.get(node.right!)!;ctx.strokeStyle="#73e6ce";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(point.x,left.y);ctx.lineTo(point.x,right.y);ctx.moveTo(point.x,left.y);ctx.lineTo(left.x,left.y);ctx.moveTo(point.x,right.y);ctx.lineTo(right.x,right.y);ctx.stroke();paint(node.left!);paint(node.right!);};paint(root);ctx.font="600 14px ui-monospace";ctx.fillStyle="#e7f1ff";ctx.textBaseline="middle";for(const leaf of leaves){const point=positions.get(leaf)!;ctx.fillText(leaf.name??"Sequence",point.x+8,point.y);}ctx.fillStyle="#9fb2c9";ctx.font="13px system-ui";ctx.fillText(`UPGMA · p-distance · ${Math.min(64,sequences.length)} taxa · up to 5,000 informative sites`,margin,canvas.height-10);return canvas;}

function renderAlignment(sequences:Sequence[],length:number,container:HTMLElement):void{const grid=container.createDiv({cls:"meta-quest-fasta-grid"});for(const item of sequences){grid.createDiv({cls:"meta-quest-fasta-id",text:item.id});const row=grid.createDiv({cls:"meta-quest-fasta-sequence"});for(const residue of item.sequence.slice(0,10_000)){const cell=row.createSpan({text:residue});cell.style.backgroundColor=residueColor(residue);}}if(length>10_000)container.createDiv({cls:"meta-quest-fasta-warning",text:"Preview limited to 10,000 residues per sequence."});}
function renderDistanceMatrix(sequences:Sequence[],container:HTMLElement):void{const selected=sequences.slice(0,24),table=container.createEl("table",{cls:"meta-quest-fasta-matrix"}),head=table.createEl("thead").createEl("tr");head.createEl("th",{text:"Taxon"});selected.forEach((_,i)=>head.createEl("th",{text:String(i+1)}));const body=table.createEl("tbody");selected.forEach((a,i)=>{const row=body.createEl("tr");row.createEl("th",{text:`${i+1}. ${a.id}`});selected.forEach((b,j)=>row.createEl("td",{text:i===j?"—":pDistance(a.sequence,b.sequence).toFixed(3)}));});}

export function renderFasta(source:string,container:HTMLElement):void{const sequences=parseFasta(source);container.empty();container.addClass("meta-quest-fasta");if(!sequences.length){container.createDiv({cls:"meta-quest-fasta-error",text:"No valid FASTA sequences found."});return;}const length=Math.max(...sequences.map(item=>item.sequence.length)),normalized=sequences.map(item=>({...item,sequence:item.sequence.padEnd(length,"-")}));container.createDiv({cls:"meta-quest-fasta-title",text:`FASTA · ${normalized.length} sequences · ${length} residues`});const toolbar=container.createDiv({cls:"meta-quest-fasta-toolbar"}),alignmentButton=toolbar.createEl("button",{text:"Alignment"}),treeButton=toolbar.createEl("button",{text:"UPGMA tree"}),matrixButton=toolbar.createEl("button",{text:"Distances"}),viewport=container.createDiv({cls:"meta-quest-fasta-viewport"});const showAlignment=()=>{viewport.empty();renderAlignment(normalized,length,viewport);};alignmentButton.onclick=showAlignment;treeButton.onclick=()=>{viewport.empty();if(normalized.length<2){viewport.createDiv({cls:"meta-quest-fasta-error",text:"At least two sequences are required to infer a tree."});return;}viewport.createDiv({cls:"meta-quest-fasta-status",text:"Inferring UPGMA tree…"});requestAnimationFrame(()=>{const tree=buildUpgma(normalized);viewport.empty();if(tree)viewport.append(drawTree(tree,normalized));});};matrixButton.onclick=()=>{viewport.empty();renderDistanceMatrix(normalized,viewport);};showAlignment();}
