import { requestUrl } from "obsidian";

type Config={taxon:string;source:string;center:[number,number];zoom:number;style:string};
const cache=new Map<string,Promise<{dataUrl:string;name:string}>>();
function parse(source:string):Config{const c:Config={taxon:"",source:"gbif",center:[-15,-55],zoom:2,style:"classic.point"};for(const line of source.split(/\r?\n/u)){const m=line.match(/^([\w-]+)\s*:\s*(.*?)\s*$/u);if(!m)continue;const k=m[1].toLowerCase(),v=m[2];if(k==="taxon")c.taxon=v.trim().slice(0,180);else if(k==="source")c.source=v.trim().toLowerCase();else if(k==="style")c.style=v.trim().replace(/[^a-z0-9.-]/giu,"")||c.style;else if(k==="zoom")c.zoom=Math.max(1,Math.min(5,parseInt(v,10)||2));else if(k==="center"){const n=v.match(/-?\d+(?:\.\d+)?/gu)?.map(Number);if(n&&n.length>=2&&n.every(Number.isFinite))c.center=[n[0],n[1]];}}return c;}
function tile(lat:number,lon:number,z:number){const scale=2**z,r=Math.max(-85.0511,Math.min(85.0511,lat))*Math.PI/180;return{x:Math.floor((lon+180)/360*scale),y:Math.floor((1-Math.asinh(Math.tan(r))/Math.PI)/2*scale),scale};}
type DecodedImage=ImageBitmap|HTMLImageElement;
async function decodeImage(blob:Blob):Promise<DecodedImage|null>{if(!blob.size)return null;try{return await createImageBitmap(blob);}catch{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error??new Error("Image decode failed"));reader.readAsDataURL(blob);}),image=new Image();image.decoding="async";image.src=dataUrl;await image.decode();return image;}}
async function bitmap(url:string,optional=false):Promise<DecodedImage|null>{const r=await requestUrl({url});if(optional&&r.status===204)return null;if(r.status<200||r.status>=300)throw new Error(`HTTP ${r.status}`);let image;try{image=await decodeImage(new Blob([r.arrayBuffer],{type:String(r.headers["content-type"]||"image/png")}));}catch(error){throw new Error(`Decode failed for ${url} (HTTP ${r.status}, ${r.arrayBuffer.byteLength} bytes): ${error instanceof Error?error.message:String(error)}`);}if(!image&&!optional)throw new Error("Empty image response");return image;}
function closeImage(image:DecodedImage|null){if(image&&"close" in image)image.close();}
async function raster(c:Config){const key=JSON.stringify(c);if(cache.has(key))return cache.get(key)!;const pending=(async()=>{if(!c.taxon)throw new Error("No taxon configured.");if(c.source!=="gbif")throw new Error(`Unsupported source: ${c.source}`);const match=await requestUrl({url:`https://api.gbif.org/v1/species/match?name=${encodeURIComponent(c.taxon)}`}),taxon=match.json as {usageKey?:number;speciesKey?:number;scientificName?:string},taxonKey=Number(taxon.usageKey??taxon.speciesKey);if(!Number.isFinite(taxonKey))throw new Error(`Taxon not found: ${c.taxon}`);const canvas=document.createElement("canvas");canvas.width=900;canvas.height=600;const ctx=canvas.getContext("2d",{alpha:false});if(!ctx)throw new Error("Canvas unavailable.");ctx.fillStyle="#07111d";ctx.fillRect(0,0,900,600);const center=tile(c.center[0],c.center[1],c.zoom),jobs=[];for(let row=0;row<2;row++)for(let column=0;column<3;column++){const x=((center.x+column-1)%center.scale+center.scale)%center.scale,y=Math.max(0,Math.min(center.scale-1,center.y+row-1)),base=`https://tile.gbif.org/3857/omt/${c.zoom}/${x}/${y}@1x.png?style=gbif-dark`,density=`https://api.gbif.org/v2/map/occurrence/density/${c.zoom}/${x}/${y}@1x.png?srs=EPSG:3857&taxonKey=${taxonKey}&style=${encodeURIComponent(c.style)}`;jobs.push(Promise.all([bitmap(base),bitmap(density,true)]).then(([b,d])=>({column,row,b,d})));}for(const t of await Promise.all(jobs)){if(!t.b)continue;ctx.drawImage(t.b,t.column*300,t.row*300,300,300);if(t.d)ctx.drawImage(t.d,t.column*300,t.row*300,300,300);closeImage(t.b);closeImage(t.d);}const name=taxon.scientificName||c.taxon,g=ctx.createLinearGradient(0,0,0,92);g.addColorStop(0,"rgba(3,8,16,.92)");g.addColorStop(1,"rgba(3,8,16,0)");ctx.fillStyle=g;ctx.fillRect(0,0,900,92);ctx.fillStyle="#f3f8ff";ctx.font="700 28px system-ui";ctx.fillText(name,20,38);ctx.fillStyle="#aabbd0";ctx.font="18px system-ui";ctx.fillText("GBIF occurrence density · observer coverage affects apparent concentration",20,68);ctx.fillStyle="rgba(3,8,16,.78)";ctx.fillRect(0,566,900,34);ctx.fillStyle="#9badc2";ctx.font="15px system-ui";ctx.textAlign="right";ctx.fillText("© OpenStreetMap · OpenMapTiles · GBIF",884,588);return{dataUrl:canvas.toDataURL("image/jpeg",.88),name};})();cache.set(key,pending);while(cache.size>10)cache.delete(cache.keys().next().value);try{return await pending;}catch(e){cache.delete(key);throw e;}}
function centerAfterDrag(center:[number,number],dx:number,dy:number,zoom:number,width:number,height:number):[number,number]{const scale=2**zoom,lat=Math.max(-85.0511,Math.min(85.0511,center[0]))*Math.PI/180;let x=(center[1]+180)/360*scale,y=(1-Math.asinh(Math.tan(lat))/Math.PI)/2*scale;x-=dx/Math.max(1,width)*3;y-=dy/Math.max(1,height)*2;const lon=(((x%scale)+scale)%scale)/scale*360-180,clamped=Math.max(0,Math.min(scale,y)),newLat=Math.atan(Math.sinh(Math.PI*(1-2*clamped/scale)))*180/Math.PI;return[newLat,lon];}

export async function renderSpeciesMap(source:string,container:HTMLElement){const c=parse(source);container.addClass("meta-quest-species-map");const bar=container.createDiv({cls:"meta-quest-species-map-toolbar"}),status=bar.createSpan({text:"Loading GBIF occurrence map…"}),minus=bar.createEl("button",{text:"−",attr:{"aria-label":"Zoom out"}}),plus=bar.createEl("button",{text:"+",attr:{"aria-label":"Zoom in"}}),image=container.createEl("img",{cls:"meta-quest-species-map-image",attr:{alt:"Species occurrence map",draggable:"false"}});image.style.cursor="grab";image.style.touchAction="none";image.style.userSelect="none";let generation=0;const update=async()=>{const current=++generation;status.setText("Loading GBIF occurrence map…");try{const result=await raster(c);if(current!==generation)return;image.src=result.dataUrl;image.alt=`Occurrence map for ${result.name}`;status.setText(`${result.name} · zoom ${c.zoom} · drag to pan`);}catch(e){if(current===generation)status.setText(`Map unavailable: ${e instanceof Error?e.message:String(e)}`);}};minus.onclick=()=>{c.zoom=Math.max(1,c.zoom-1);void update();};plus.onclick=()=>{c.zoom=Math.min(5,c.zoom+1);void update();};let drag:null|{id:number;x:number;y:number;dx:number;dy:number}=null;image.addEventListener("pointerdown",(event)=>{if(event.button!==0&&event.pointerType==="mouse")return;drag={id:event.pointerId,x:event.clientX,y:event.clientY,dx:0,dy:0};image.setPointerCapture(event.pointerId);image.style.cursor="grabbing";event.preventDefault();});image.addEventListener("pointermove",(event)=>{if(!drag||event.pointerId!==drag.id)return;drag.dx=event.clientX-drag.x;drag.dy=event.clientY-drag.y;image.style.transform=`translate(${drag.dx}px,${drag.dy}px) scale(1.025)`;event.preventDefault();});const finish=(event:PointerEvent)=>{if(!drag||event.pointerId!==drag.id)return;const {dx,dy}=drag;drag=null;image.style.cursor="grab";image.style.transform="";if(Math.hypot(dx,dy)<4)return;c.center=centerAfterDrag(c.center,dx,dy,c.zoom,image.clientWidth,image.clientHeight);void update();};image.addEventListener("pointerup",finish);image.addEventListener("pointercancel",finish);await update();}
